### ISSUE TITLE
Use image optimizer bot on PRs

### ISSUE THREAD

**Issue by murlakatamenka** [catppuccin/wallpapers#23]
It makes sense to use such bot since the repo focuses heavily on images. Like https://github.com/apps/imgbot/

For example, [`forrest.png`](https://github.com/catppuccin/wallpapers/blob/99f3011c628a50dc8a57429f010e41036dd6383d/landscapes/forrest.png) can be reduced almost 2x!

![image](https://user-images.githubusercontent.com/7361274/162729237-dad76d9a-04a6-4a50-abab-623e2c4af322.png)

**Comment by murlakatamenka** [comment]
Well, you don't provide any links, so it's hard to judge. But lossless image optimizers (like `oxipng` I've used above) don't change a single pixel of the image, just make image internals take less bytes.

> Imgbot uses _lossless_ compression by default.

**Comment by murlakatamenka** [comment]
Just in case, I'm not affiliated with that not in any case, just gave an advice I though would be helpful

**Comment by nekowinston** [comment]
This has been open for a while, and I just merged #31 today, which is a good first step.

I'll set up the Bot when I have the time.

**Comment by nekowinston** [comment]
Forgot to close this, I've added [ImgBot](https://github.com/apps/imgbot/), just waiting for future PRs. 🙂 

Thanks again for the suggestion 👍
