### ISSUE TITLE
Offer wallpapers in higher resolution than 1920x1080 if available

### ISSUE THREAD

**Issue by johkneisl** [catppuccin/wallpapers#24]
These days, displays with a resolution higher than 1920x1080 are really not all that uncommon.
It would be nice to offer all wallpapers in higher resolutions if possible.
Especially for machine generated ones (gradients etc), this shouldn't bee too difficult.

**Comment by pws1453** [comment]
Are original sources provided for the wallpapers in this repository? This may be a good place to start.

**Comment by Lucaffo** [comment]
I think a good improvements could be to organize folder in a different way.

Like: 
Wallpapers/<Resolution>/<Context>/<File>

Or like that i like better:
Wallpapers/<Theme>/<FileName>/<FileAtResoluton>.png

**Comment by nekowinston** [comment]
❓ there's little reason to keep several resolutions in this git repo.

We'll just make the highest resolution available (aiming for 4k), since every single wallpaper preference pane, or CLI like `feh` can scale it down to screen size.
