### ISSUE TITLE
Improve text rendering on minimalistic/*-cat wallpapers

### ISSUE THREAD

**Issue by yellowsink** [catppuccin/wallpapers#25]
I use the magenta cat wallpaper on my desktop, but I couldn't help but notice the (forgive my bluntness) horrific text rendering quality, which if fixed would make the wallpapers much more pleasing to look at.

(See greyscale pixels all around the text)
![image](https://user-images.githubusercontent.com/19270622/164112117-89890e2d-811d-47b1-8b09-68837ce06a81.png)
![image](https://user-images.githubusercontent.com/19270622/164112130-e85bc84c-b1b2-4c9a-8700-a978196c78fc.png)
![image](https://user-images.githubusercontent.com/19270622/164112148-1a2453d9-0a19-4b4e-88af-970a0750a4a1.png)

**Comment by Gingeh** [comment]
How does this look?
![magenta-cat](https://user-images.githubusercontent.com/39150378/164120074-9303e5dd-0f85-4f7f-9a6d-59055aa13637.png)
(The cat is slightly different because I don't know which font was originally used.)

**Comment by andreasgrafen** [comment]
Better, by a lot! At least in my view. I also don't think that it's an issue that the art looks slightly different. c:

**Comment by yellowsink** [comment]
looks miles better, but i think it looks better with the original font, ill have to try and track it down

**Comment by yellowsink** [comment]
It looks kinda like DejaVu Sans Mono but I dont think it is

**Comment by Gingeh** [comment]
I found the original! The font is Consolas!

**Comment by Gingeh** [comment]
hmm, it still looks different..
![magenta-cat-consolas](https://user-images.githubusercontent.com/39150378/164259924-c4d36b7b-78d9-4a81-bf66-fa7cfe1b261f.png)

**Comment by andreasgrafen** [comment]
Maybe it isn't really a slash but a `╱`?
[https://unicode-table.com/en/2571/](https://unicode-table.com/en/2571/)

**Comment by yellowsink** [comment]
hm not quite
![image](https://user-images.githubusercontent.com/19270622/164305074-7cd7c923-bede-4907-a3d1-2db566ccc157.png)

**Comment by andreasgrafen** [comment]
What about this one maybe? `⟋`
[https://unicode-table.com/en/27CB/](https://unicode-table.com/en/27CB/)

**Comment by yellowsink** [comment]
bang on!

old:
![image](https://user-images.githubusercontent.com/19270622/164313910-c6273c29-7d46-4176-9c53-cd3f34604da5.png)

my recreation:
![image](https://user-images.githubusercontent.com/19270622/164313932-c965a7ae-37d2-48e8-bd68-78c747b0ad97.png)

**Comment by yellowsink** [comment]
Not perfect but i propose
[testing.xcf.zip](https://github.com/catppuccin/wallpapers/files/8525026/testing.xcf.zip)
:
