### ISSUE TITLE
add new flavors

### ISSUE THREAD

**Issue by max397574** [catppuccin/wallpapers#27]
whoever added e.g. the minimalistic buttons wallpaper or the ones with the ascii cats
would it be possible to add those with the new flavors as well?

**Comment by nonetrix** [comment]
anime flavor would be cool to get up doots on r*ddit as well I think

**Comment by isabelincorp** [comment]
Coming back to this issue months later, I think it would be cool to redo the minimalistic wallpapers to fit in all 4 flavours. I'll definitely look into redoing them.

**Comment by andreasgrafen** [comment]
For the kittens I can offer this: https://www.dropbox.com/sh/jpouvkkyzw77bs6/AACdqY2cBNVMyVxPKc4GA3qVa?dl=0

**Comment by isabelincorp** [comment]
Unless we figure out how to make that fit without having to scroll down for hours, I would say just have only the base versions of each latte/frappe/macchiato/mocha wallpaper

**Comment by andreasgrafen** [comment]
> how to make that fit without having to scroll down for hours

<details>
<summary>closed details</summary>
mabe? :D
</details>

**Comment by isabelincorp** [comment]
mhm just gotta figure out a way to do that around the automation (that I really don't understand), I'll join vc in a min
