### ISSUE TITLE
How long will this repository be down for?

### ISSUE THREAD

**Issue by joeyshi12** [catppuccin/wallpapers#39]
Will this reworking take longer than a few weeks?

**Comment by shadowninja55** [comment]
also, why was the commit history seemingly deleted? at least we'd be able to view the wallpapers if it'd been left intact, and i don't see the point of removing it.

**Comment by nekowinston** [comment]
@joeyshi12 
> Will this reworking take longer than a few weeks?

Difficult to say, I don't have much motivation to work on this repo, as I see that Git is the wrong medium for wallpapers.

@shadowninja55 
>  i don't see the point of removing it.

It was a mistake to accept some of the PRs introducing derivative works where the License of the original image doesn't permit modification. We have to reverse-image search to find the originals, check the license, credit the author - if we can't find it, we have to ask the original submitter.
Expect `./landscapes/` to be empty when the repository returns, only a README will exist, with links to the original sources.

> why was the commit history seemingly deleted?

The repository has been duplicated as a private repo internally, every maintainer has access to it.
<img width="643" alt="image" src="https://user-images.githubusercontent.com/79978224/191136504-49ec6c47-eb32-487f-9530-296fe188f105.png">
History remains intact, while this one has been squash merged into a single commit for the time being.

Once it's sorted out, we'll force-push the reworked repo here.

<hr/>

In future we'll only accept PRs where either:
- The PR author is the author of the wallpaper themselves
- The license is linked to and the OC credited
- It's just a link to a nice wallpaper that fits Catppuccin

**Comment by umop3plsdn** [comment]
Hopefully it will come back.. Definitely understand the hard work that goes into reviewing the PRs though and appreciate the effort. Kinda sad to see that it's gone

**Comment by Suyashtnt** [comment]
is there any ETA for when this repo will be back? I wanna ~~steal~~ get some wallpapers from here. Thanks for the effort put into this repo and now reviewing PRs.

**Comment by nekowinston** [comment]
I forgot to respond to this issue when closing it yesterday.

The old wallpapers are back now, and I'll add a contributing template soon, so we can work through a simple checklist when people want to contribute their wallpapers.

**Comment by umop3plsdn** [comment]
Thank you so much
