### ISSUE TITLE
Adding a wallpaper

### ISSUE THREAD

**Issue by urgellx** [catppuccin/wallpapers#54]
I don't know how to make a pull request, but I'd like to contribute with this little image.
![Catbsolu](https://user-images.githubusercontent.com/109094729/207421426-50ae45e2-8d84-4108-abb4-3d2c81e237af.jpg)

If this gets  added,  i just want to say that my username is urgelle and not urgellx.

**Comment by isabelincorp** [comment]
Thanks for the PR! I will get around to this relatively soon, if you need to know how to make a PR, make a fork, clone your repository, cd into the repo then `git checkout 0.2.0` (The branch I am working on), make your changes push and commit, then on your repository's github page there is a button that says "Contribute" use that to make your PR.
