### ISSUE TITLE
Add wallpaper

### ISSUE THREAD

**Issue by Spaxly** [catppuccin/wallpapers#56]
![cat_leaves](https://user-images.githubusercontent.com/68564017/210008590-77328632-dd17-408a-9430-f9afaa76333d.png)
This isn't mine, I got it from rxyhn but since its catppuccin and not here, well now here it is.

**Comment by dscoder421** [comment]
It looks cool, do you have the link to the original file?

**Comment by Spaxly** [comment]
> It looks cool, do you have the link to the original file?

Unfortunately, I don't have a direct link, though it is from one of rxyhn's repos.

**Comment by dscoder421** [comment]
Create a PR with the image you added in the issue, if it is 1920x1080

**Comment by Spaxly** [comment]
File uploading is disabled for PR

**Comment by dscoder421** [comment]
Close and open another PR and commit the file over there
